replicaCount: 1

image:
  repository: ghcr.io/jdiegosierra/revolut-test
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80 