name: Docker and Helm Chart Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/images/${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Chart Version
        id: chart
        run: |
          CHART_VERSION=$(helm show chart charts/app | grep '^version:' | awk '{print $2}')
          echo "version=${CHART_VERSION}" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.chart.outputs.version }}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=sha-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.12.0'

      - name: Package Helm Chart
        id: package
        run: |
          helm package charts/app -d ./helm-packages
          CHART_VERSION=$(helm show chart charts/app | grep '^version:' | awk '{print $2}')
          CHART_NAME=$(helm show chart charts/app | grep '^name:' | awk '{print $2}')
          mv ./helm-packages/${CHART_NAME}-${CHART_VERSION}.tgz ./helm-packages/${CHART_NAME}.tgz
          echo "chart_name=${CHART_NAME}" >> $GITHUB_OUTPUT

      - name: Push Helm Chart to GitHub Packages
        run: |
          helm push ./helm-packages/${{ steps.package.outputs.chart_name }}.tgz oci://chart/${{ github.repository }} 